cursor #e6e1e4
cursor_text_color #cbc4ce

foreground            #e6e1e4
background            #141315
selection_foreground  #342e3c
selection_background  #cdc3d5
url_color             #d2bee9

color0   #141315
color1   #ff728c
color2   #74e98f
color3   #ffdb72
color4   #c3acdd
color5   #58476b
color6   #d2bee9
color7   #ece5f4
color8   #918c97
color9   #ff9fb0
color10  #a5ffba
color11  #ffe8a5
color12  #e9d6ff
color13  #eddeff
color14  #f3e9ff
color15  #fbf8ff
